services:
  w2d:
    container_name: w2d
    image: zoeyvid/w2d-docker
    restart: always
    volumes:
      - "/opt/w2d/storage:/app/storage"
      - "/opt/w2d/downloads:/app/downloads"
    environment:
      - "TZ=Europe/Berlin"
      - "WA2DC_TOKEN=your-discord-bot-token"
    user: 1000:1000
